{{- if eq .Values.productionBranch .Values.images.app.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: quant-ingress
  labels:
    app: quant-ingress
spec:
  selector:
    matchLabels:
      app: quant-ingress
  template:
    metadata:
      labels:
        app: quant-ingress
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        ### BEGIN INGRESS CONTAINER
        - name: ingress
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: registry.quant.cloud/quant-public/ingress:1.0.11
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: ".25Gi"
              cpu: "200m"
            limits:
              memory: ".25Gi"
              cpu: "200m"
        ### END INGRESS CONTAINER
 {{- end }}